In [44]:
import numpy as np
ar=np.arange(1024)

In [45]:
ar1=ar.reshape(128,8)
print(ar1)

[[   0    1    2 ...    5    6    7]
 [   8    9   10 ...   13   14   15]
 [  16   17   18 ...   21   22   23]
 ...
 [1000 1001 1002 ... 1005 1006 1007]
 [1008 1009 1010 ... 1013 1014 1015]
 [1016 1017 1018 ... 1021 1022 1023]]


In [46]:
ar2=ar.reshape(32,32)
print(ar2)

[[   0    1    2 ...   29   30   31]
 [  32   33   34 ...   61   62   63]
 [  64   65   66 ...   93   94   95]
 ...
 [ 928  929  930 ...  957  958  959]
 [ 960  961  962 ...  989  990  991]
 [ 992  993  994 ... 1021 1022 1023]]


In [47]:
ar3=ar.reshape(16,64)
print(ar3)

[[   0    1    2 ...   61   62   63]
 [  64   65   66 ...  125  126  127]
 [ 128  129  130 ...  189  190  191]
 ...
 [ 832  833  834 ...  893  894  895]
 [ 896  897  898 ...  957  958  959]
 [ 960  961  962 ... 1021 1022 1023]]


In [48]:
ar4=ar.reshape(256,4)
print(ar4)

[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 ...
 [1012 1013 1014 1015]
 [1016 1017 1018 1019]
 [1020 1021 1022 1023]]
